name: CI on Dev

on:
  pull_request:
    branches: [ "dev" ]

env:
  NEXT_PUBLIC_RUN_MODE: ${{secrets.NEXT_PUBLIC_RUN_MODE_DEV}}
  NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL_DEV}}
  NOTION_API: ${{secrets.NOTION_API}}
  TZ: Asia/Seoul

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Run lint
      run: yarn run lint

    # - name: Run tests
    #   run: yarn test

    - name: Run build
      run: yarn build
